# Generated by Django 4.0.6 on 2022-11-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artible',
            new_name='Article',
        ),
    ]
