# Generated by Django 3.2.15 on 2022-10-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='deadline',
            new_name='headline',
        ),
    ]
