# Generated by Django 3.2.15 on 2022-11-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytoone', '0002_rename_deadline_article_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='last_name',
        ),
    ]
